# Postgres datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/career_platform?currentSchema=public
spring.datasource.username=career_user
spring.datasource.password=chaimanour@22
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=public

# JWT settings
jwt.secret=change_this_to_a_strong_secret
jwt.expiration=900000

# File Upload Configuration
cv.upload.dir=uploads/cvs/
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB